### ISSUE TITLE
1번째 영역 내용 배치하기

### ISSUE THREAD

**Issue by bell2lee** [wwjdtm/G2Mh-p#3]
반응형 @media를 사용할 것.

글자 크게크게 시워ㅓㅓㅓㅓㅓㅓㅓㅓㅓㅓ어언하게

**Comment by wwjdtm** [comment]
아직도 자료를 보내주지않아쏘요,, 반응형으로 먼저 만들어보겠쑴다 !

**Comment by wwjdtm** [comment]
ㄷ..됐을까요 !!?!

**Comment by bell2lee** [comment]
커밋 203f791을 참고하세용
