### ISSUE TITLE
1번 컨텐츠 CSS & JS 디자인

### ISSUE THREAD

**Issue by bell2lee** [wwjdtm/G2Mh-p#5]
로고 슬로건
인사말

**Comment by wwjdtm** [comment]
디자인이 정말,, 별루인것같숩니당,,흑흑,, 
그리고 회사에서 보내주신 로고가 ,, 이미지파일이 아니라서 캡쳐해서 누끼를 따봤는데
흰색이 쪼금쪼금 남아있어서 흰배경 이외에는 로고를 배치할 수 가 없더라구용 
감안해서,,,ㅂ,,,봐주세요,<!
![image](https://user-images.githubusercontent.com/28584133/83749740-29d42000-a69f-11ea-84c9-55ffc8cbc34b.png)

**Comment by bell2lee** [comment]
로고를 푸터영역으로 넣는건 어떻게 생각해용?

**Comment by bell2lee** [comment]
전체적인 디자인 잡기

Adobe color에 로고색, 글자색 코드를 넣어 나오는 색상 5개를 가지고

배경, 글자색, 제목색 등 각 항목 별 색상을 통일 하도록.

또한 상단에 들어갈 그래픽 이미지를 찾아보고 5개의 후보를 정해서 가공 후 사용.

**Comment by wwjdtm** [comment]
이거 글씨색상 #21857C 도 어도비 참고해써요 -!
![Uploading image.png…]()
다른것도 찾아볼께요오

**Comment by bell2lee** [comment]
1번 컨텐츠 아래에 있는 이미지 img 태그 -> div태그로 변경 후 background-size 속성을 이용해 비율에 맞게 늘리기

**Comment by wwjdtm** [comment]
이렇게 수정하면 되나용 🤓

**Comment by bell2lee** [comment]
https://www.codingfactory.net/10559

https://aboooks.tistory.com/162

.image{
    background: url('image.jpg') center center;
    width: 100%;
    height: 300px;
    background-size: cover;
}

이렇게 수정하면 되는데

background 에 center center 이 의미하는 바, background-size:cover이 의미하는 바를 공부해야해요 

상단 두 개의 링크를 참고하세용

**Comment by bell2lee** [comment]
<img width="1679" alt="스크린샷 2020-06-06 오후 4 56 17" src="https://user-images.githubusercontent.com/28583579/83939271-a5a4a880-a816-11ea-961a-094f9da7ca3a.png">
이런 화면이 나와야 해요  이미지의 비율을 유지하면서 최대 사이즈로 보이게 해야 예쁘게 보여요

**Comment by wwjdtm** [comment]
넵 수정할께용 !-!
